/*
 * opdm_hal_def.h
 *
 *  Created on: 28 de abr de 2023
 *      Author: breno
 */

#ifndef __OPDM_HAL_DEF_H_
#define __OPDM_HAL_DEF_H_


#include "stm32f1xx_hal.h"
#include "stm32f1xx_hal_def.h"
#include "pdm_def.h"

// ----------------- GPIO Defines -----------------
// These are the GPIO ports and pins that are used by the OPDM driver.
// They were generated by CubeIDE.
#define INTERNAL_LED_Pin GPIO_PIN_13
#define INTERNAL_LED_GPIO_Port GPIOC
#define MUX_INPUTS_A1_Pin GPIO_PIN_14
#define MUX_INPUTS_A1_GPIO_Port GPIOC
#define MUX_INPUTS_A2_Pin GPIO_PIN_15
#define MUX_INPUTS_A2_GPIO_Port GPIOC
#define CURRENT_VOLTAGE_SENSE_ADC_PIN_Pin GPIO_PIN_0
#define CURRENT_VOLTAGE_SENSE_ADC_PIN_GPIO_Port GPIOA
#define AD_INPUTS_ADC_PIN_Pin GPIO_PIN_1
#define AD_INPUTS_ADC_PIN_GPIO_Port GPIOA
#define STATUS_LED_Pin GPIO_PIN_3
#define STATUS_LED_GPIO_Port GPIOA
#define GATE_LC0_SIG_Pin GPIO_PIN_4
#define GATE_LC0_SIG_GPIO_Port GPIOA
#define GATE_LC1_SIG_Pin GPIO_PIN_5
#define GATE_LC1_SIG_GPIO_Port GPIOA
#define GATE_LC2_SIG_Pin GPIO_PIN_6
#define GATE_LC2_SIG_GPIO_Port GPIOA
#define GATE_LC3_SIG_Pin GPIO_PIN_7
#define GATE_LC3_SIG_GPIO_Port GPIOA
#define GATE_HC1_SIG_Pin GPIO_PIN_0
#define GATE_HC1_SIG_GPIO_Port GPIOB
#define GATE_HC0_SIG_Pin GPIO_PIN_1
#define GATE_HC0_SIG_GPIO_Port GPIOB
#define GATE_HC3_SIG_Pin GPIO_PIN_10
#define GATE_HC3_SIG_GPIO_Port GPIOB
#define GATE_HC2_SIG_Pin GPIO_PIN_11
#define GATE_HC2_SIG_GPIO_Port GPIOB
#define CANC_INTERRUPT_Pin GPIO_PIN_8
#define CANC_INTERRUPT_GPIO_Port GPIOA
#define CANB_ERR_Pin GPIO_PIN_9
#define CANB_ERR_GPIO_Port GPIOA
#define CANB_STB_Pin GPIO_PIN_10
#define CANB_STB_GPIO_Port GPIOA
#define MUX_CUR_SENSE_A3_Pin GPIO_PIN_15
#define MUX_CUR_SENSE_A3_GPIO_Port GPIOA
#define MUX_CUR_SENSE_A2_Pin GPIO_PIN_3
#define MUX_CUR_SENSE_A2_GPIO_Port GPIOB
#define MUX_CUR_SENSE_A1_Pin GPIO_PIN_4
#define MUX_CUR_SENSE_A1_GPIO_Port GPIOB
#define MUX_CUR_SENSE_A0_Pin GPIO_PIN_5
#define MUX_CUR_SENSE_A0_GPIO_Port GPIOB
#define CANB_EN_Pin GPIO_PIN_6
#define CANB_EN_GPIO_Port GPIOB
#define MUX_INPUTS_A0_Pin GPIO_PIN_7
#define MUX_INPUTS_A0_GPIO_Port GPIOB


typedef enum{
	DIGITAL_ACTIVE_H = 0,
	DIGITAL_ACTIVE_L,
	LINEAR_ANALOG,
	CALIBRATED_ANALOG,
	ROTARY_SWITCH,
	NUM_OF_INPUT_TYPES
}OPDM_INPUT_TYPE;


typedef struct
{
	GPIO_TypeDef *port;
    uint16_t pin;
}PDM_HAL_PortPinTypedef;

#endif /* OPDM_DRIVER_INC_OPDM_HAL_DEF_H_ */
